language: php

# Define the php versions against we want to test our code
php:
    - 7.1

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install --dev --no-interaction

after_success:
    - bash <(curl -s https://codecov.io/bash)
